---
title: "Assignment_11"
author: "Author: Megan Xiao\n"
date: "Date: 2025-11-10"
output: html_document
---

## Buggy Code

```{r}
tukey_multiple <- function(x) {
  outliers <- array(TRUE, dim = dim(x))
  for (j in 1:ncol(x)) { 
    outliers[, j] <- outliers[, j] & tukey.outlier(x[,j]) 
  }
  outlier.vec <- vector("logical", length = nrow(x))
  for (i in 1:nrow(x)) {
    outlier.vec[i] <- all(outliers[i, ])
  }
  return(outlier.vec)
}
```

## Reproduce the Error

```{r}
set.seed(123)
test_mat <- matrix(rnorm(50), nrow = 10)
tukey_multiple(test_mat)
```

## Diagnose the Bug


## Fix the Code

```{r}
# Corrected inside the loop:
outliers[, j] <- outliers[, j] & tukey.outlier(x[, j])
```

```{r}
tukey.outlier <- function(x){
  q1 <- quantile(x, 0.25)
  q3 <- quantile(x, 0.75)
  iqr <- q3 - q1
  lower_fence <- q1 - (1.5 * iqr)
  upper_fence <- q3 + (1.5 * iqr)
  
 is_outlier <- (x < lower_fence) | (x > upper_fence)
 return(is_outlier)
}
```

## Validate Your Fix

```{r}
corrected_tukey <- function(x) {
  outliers <- array(TRUE, dim = dim(x))
  for (j in seq_len(ncol(x))) {
    outliers[, j] <- outliers[, j] & tukey.outlier(x[, j])
  }
  outlier.vec <- logical(nrow(x))
  for (i in seq_len(nrow(x))) {
    outlier.vec[i] <- all(outliers[i, ])
  }
  outlier.vec
}

corrected_tukey(test_mat)
```

## Defensive Enhancements

```{r}
corrected_tukey <- function(x) {
  result <- tryCatch({
    all_numeric <- all(sapply(x, is.numeric))
    stopifnot(all_numeric)
  }, error = function(e) {
    print("Matrix is not numeric")
  })
    outliers <- array(TRUE, dim = dim(x))
  for (j in seq_len(ncol(x))) {
    outliers[, j] <- outliers[, j] & tukey.outlier(x[, j])
  }
  outlier.vec <- logical(nrow(x))
  for (i in seq_len(nrow(x))) {
    outlier.vec[i] <- all(outliers[i, ])
  }
  
  return(outlier.vec)
  
}
```

```{r}
str_mat <- matrix(c("a","b","c","d"),nrow =2, ncol = 2)
new_row <- c(1,2)
str_mat <- rbind(str_mat,new_row)
```

```{r}
corrected_tukey(test_mat)
```

```{r}
corrected_tukey(str_mat)
```